set_clock: set_clock.c si_comm.c si_ui.c display.c clock.c si_ui.h si_comm.h display.h clock.h
	gcc set_clock.c si_comm.c si_ui.c display.c clock.c -g  -o set_clock -Wall -lpthread

clean:
	rm -f set_clock *~ *.o
